# You must change these to your own details.
[package]
name = "characteristics_method"
version = "0.1.0"
authors = ["zetanumbers <zeta0.114942@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2.73"
js-sys = "0.3.50"
seed = "0.8.0"
